### ISSUE TITLE
LTUpdate keeps crashing under iOS 5.1/6.0/6.1

### ISSUE THREAD

**Issue by marzapower** [lexrus/LTUpdate#1]
Using the standard `[[LTUpdate shared] update]` call the library hangs up at line #164 in the `LTUpdate.m` file.

Using the more complex call (the one with the callback block), the library throws a couple of 
`-[CFDictionary release]: message sent to deallocated instance 0xb0dcf80`
error messages.

Maybe it's an ARC-related problem?

**Comment by marzapower** [comment]
I am using this library through CocoaPods. And I also have JSONKit installed (as it's required by another library).

**Comment by lexrus** [comment]
@marzapower I've fixed the issue and moved the tag to the latest commit. So you should remove {{your project path}}/Pods/LTUpdate and then `pod udpate` to get the latest version. Sorry for the inconvenience.

**Comment by marzapower** [comment]
You're welcome! Thank you for your quick answer.
I am going to try this revision now.

P.S. Why don't you tag it with a 1.0.0 version?

**Comment by lexrus** [comment]
It's far away from perfect. I think 0.0.1 is some kind of humility.

**Comment by marzapower** [comment]
By the way, it works really fine now.
Great job!
