### ISSUE TITLE
local notication 重复发送?

### ISSUE THREAD

**Issue by stattrak-dragonlore** [lexrus/LTUpdate#2]
- (void)applicationDidBecomeActive:(UIApplication *)application
  {
  [[LTUpdate shared] updateAndPush:LTUpdateDaily];
  }
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
  {
  [[LTUpdate shared] reduceNotification:notification];
  }

启动后退出-->  收到通知  -->  点击通知 --> 启动app->立刻跳到 App store,
这时顶部通知栏又收到一条通知

**Comment by stattrak-dragonlore** [comment]
应该在 pushLatestVersion 里面移除掉 UIApplicationDidEnterBackgroundNotification的监听把:

```
- (void)pushLatestVersion:(UILocalNotification *)notification
{
    if (!self.latestVersion) return;
    if (!notification) {
        notification = [[UILocalNotification alloc] init];
        notification.timeZone = [NSTimeZone defaultTimeZone];
        notification.fireDate = [[NSDate date] dateByAddingTimeInterval:1.5f];
        notification.alertBody = [self updateMessage];
        notification.alertAction = LTI18N(@"Update");
    }
    [[UIApplication sharedApplication] scheduleLocalNotification:notification];
+    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIApplicationDidEnterBackgroundNotification object:nil];
}
```

**Comment by lexrus** [comment]
@dengzhp 谢谢你，已经修正。
如果是用 CocoaPods 安装的，请 `rm -rf ~/Library/Caches/CocoaPods` 后在项目目录运行 `pod update`，确保下载的是最新版。
